/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { TimeCapsule } from "./TimeCapsule";
export * as factories from "./factories";
export { TimeCapsule__factory } from "./factories/TimeCapsule__factory";
