/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace TimeCapsule {
  export type CapsuleStruct = {
    creator: AddressLike;
    message: string;
    unlockTime: BigNumberish;
    id: BigNumberish;
  };

  export type CapsuleStructOutput = [
    creator: string,
    message: string,
    unlockTime: bigint,
    id: bigint
  ] & { creator: string; message: string; unlockTime: bigint; id: bigint };
}

export interface TimeCapsuleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "capsules"
      | "createCapsule"
      | "getCapsule"
      | "getUserCapsules"
      | "nextCapsuleId"
      | "userCapsules"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "CapsuleCreated"): EventFragment;

  encodeFunctionData(
    functionFragment: "capsules",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createCapsule",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCapsule",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserCapsules",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "nextCapsuleId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "userCapsules",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "capsules", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createCapsule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getCapsule", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getUserCapsules",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextCapsuleId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userCapsules",
    data: BytesLike
  ): Result;
}

export namespace CapsuleCreatedEvent {
  export type InputTuple = [
    id: BigNumberish,
    creator: AddressLike,
    unlockTime: BigNumberish
  ];
  export type OutputTuple = [id: bigint, creator: string, unlockTime: bigint];
  export interface OutputObject {
    id: bigint;
    creator: string;
    unlockTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TimeCapsule extends BaseContract {
  connect(runner?: ContractRunner | null): TimeCapsule;
  waitForDeployment(): Promise<this>;

  interface: TimeCapsuleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  capsules: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint] & {
        creator: string;
        message: string;
        unlockTime: bigint;
        id: bigint;
      }
    ],
    "view"
  >;

  createCapsule: TypedContractMethod<
    [_message: string, _unlockTime: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  getCapsule: TypedContractMethod<
    [_id: BigNumberish],
    [TimeCapsule.CapsuleStructOutput],
    "view"
  >;

  getUserCapsules: TypedContractMethod<
    [_user: AddressLike],
    [bigint[]],
    "view"
  >;

  nextCapsuleId: TypedContractMethod<[], [bigint], "view">;

  userCapsules: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "capsules"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint] & {
        creator: string;
        message: string;
        unlockTime: bigint;
        id: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "createCapsule"
  ): TypedContractMethod<
    [_message: string, _unlockTime: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getCapsule"
  ): TypedContractMethod<
    [_id: BigNumberish],
    [TimeCapsule.CapsuleStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserCapsules"
  ): TypedContractMethod<[_user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "nextCapsuleId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "userCapsules"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getEvent(
    key: "CapsuleCreated"
  ): TypedContractEvent<
    CapsuleCreatedEvent.InputTuple,
    CapsuleCreatedEvent.OutputTuple,
    CapsuleCreatedEvent.OutputObject
  >;

  filters: {
    "CapsuleCreated(uint256,address,uint256)": TypedContractEvent<
      CapsuleCreatedEvent.InputTuple,
      CapsuleCreatedEvent.OutputTuple,
      CapsuleCreatedEvent.OutputObject
    >;
    CapsuleCreated: TypedContractEvent<
      CapsuleCreatedEvent.InputTuple,
      CapsuleCreatedEvent.OutputTuple,
      CapsuleCreatedEvent.OutputObject
    >;
  };
}
